services:Add commentMore actions
  - type: web
    name: aniwatch-api
    runtime: docker
    repo: https://github.com/SAbotsup/api.git
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 4000
